baseURL = "https://kidult-joy.gitHub.io/"
languageCode = "zh_CN"
title = "唐震怡的blog"
theme = "casper"
paginate = 5 #分页每页记录数
DisqusShortname = "唐震怡" #评论时显示的名字
Copyright = "All rights reserved - 2020" #版权
canonifyurls = true

[params]
  description = "To Be Better"
  cover = "images/cover.jpg" #自己找的博客封面，要够大够酷
  author = "唐震怡" #文章作者
  authorlocation = "Beijing, China" #作者位置
  authorwebsite = "https://kidult-joy.GitHub.io/" #作者站点
  bio= "北京大学|信息管理系" #作者简介
  logo = "images/IU.jpg" #作者头像
  #googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "kidult-joy" #github用户名
  email = ""
  twitterName = "tangzhenyi2020"
  # facebookName = ""
  # linkedinName = "" #LinkedIn用户名
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false #是否显示Hugo水印
  hjsStyle = "atom-one-light"
  [params.social]
    twitter = "https://twitter.com/tangzhenyi2020"

[[menu.main]] #页面菜单参数
  name = "Home"
  weight = -1
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -2
  identifier = "about"
  url = "/post/about-me.pdf"

[[menu.main]]
  name = "Others"
  weight = -3
  identifier = "other"
  url = "/tags/others"


[permalinks]
  post = "/:year/:month/:day/:title/"
